version: "3.8"
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
    volumes:
      - weaviate_data:/var/lib/weaviate

  scraper:
    build: ./scraper
    environment:
      # Additional env vars if needed
    depends_on:
      - weaviate

  llm-service:
    build: ./llm_service
    environment:
      OPENAI_API_KEY: "your_openai_api_key"
      WEAVIATE_URL: "http://weaviate:8080"
    ports:
      - "8000:8000"
    depends_on:
      - weaviate

  airflow:
    image: apache/airflow:2.5.0
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8081:8080"  # Adjust port mapping as needed

volumes:
  weaviate_data:
